language: node_js
node_js: lts/boron

sudo: false
dist: trusty

cache: yarn

matrix:
  fast_finish: true

env:
- 'TEST_DIR=packages/eslint-config-cos-base'
- 'TEST_DIR=packages/eslint-config-cos-ember'

before_script:
- 'cd $TEST_DIR'
